services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taller_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: taller_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taller
      MYSQL_USER: taller
      MYSQL_PASSWORD: taller
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: taller_pma
    environment:
      PMA_HOST: db
      PMA_USER: taller
      PMA_PASSWORD: taller
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: {}
